apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnetdemo
  namespace: ramana
  labels:
    app: dotnetdemo
spec:
  selector:
    matchLabels:
      app: dotnetdemo
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: dotnetdemo
    spec:
      containers:
      - name: dotnetdemo
        image: venkatramanareddy1097/dotnetdemo
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 100m
            memory: 300Mi
          limits:
            cpu: 200m
            memory: 300Mi
        livenessProbe:
          exec:
            command:
            - ls
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - ls
          initialDelaySeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        ports:
        - containerPort: 80
          name: walmartdev
        imagePullPolicy: Always
      restartPolicy: Always
