apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnetdemo
  namespace: ramana
  labels:
    app: dotnetdemo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dotnetdemo
  template:
    metadata:
      labels:
        app: dotnetdemo
    spec:
      containers:
      - name: dotnetdemo
        image: venkatramanareddy1097/dotnetdemo
        ports:
        - containerPort: 5000
